//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Menus
    {
        public System.Guid ID { get; set; }
        public string sMenuName { get; set; }
        public string sMenuUrl { get; set; }
        public string sParentMenuId { get; set; }
        public string sMenuIcon { get; set; }
        public System.DateTime dInsertTime { get; set; }
        public bool bIsDeleted { get; set; }
        public int iOrder { get; set; }
    }
}
